defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pivotpong
  password:
  min_messages: warning

development:
  <<: *defaults
  database: pivotpong_development

production:
  <<: *defaults
  database: pivotpong_production

test: &test
  <<: *defaults
  database: pivotpong_test

