common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ping_pong_ladder
  password:

development:
  <<: *common
  database: ping_pong_ladder_development

test:
  <<: *common
  database: ping_pong_ladder_test

production:
  <<: *common
  database: ping_pong_ladder_production
